### ISSUE TITLE
Using `err` as error variable name causes compiler to want an identifier

### ISSUE THREAD

**Issue by emizzle** [codex-storage/questionable#62]
nim v1.6.20
macos

This was not compiling until `err` was changed to `error`:
```nim
without digest =? Poseidon2Hash.spongeDigest(bytes.toOpenArray(start, finish - 1), 2), err:
  return failure err
```
Source:
https://github.com/codex-storage/nim-codex/pull/975/files#diff-d4fdc8964c53f8772ad04bad070e544f52451bc37dc5c801eef2ab21664703c2R54-R55

But a few lines down, `err` is used and it *does* compile:
https://github.com/codex-storage/nim-codex/blob/8aaff32b4669366ca468ef7eaf04e730412ab95d/codex/utils/poseidon2digest.nim#L68-L69

The compilation error:
```
/Users/egonat/repos/codex-storage/nim-codex/codex/utils/poseidon2digest.nim(54, 92) Error: expected an identifier, got 
err(typeof(result))
stack trace: (most recent call last)
nimscript.nim(429, 18)
build.nims(30, 15)       codexTask
build.nims(23, 7)        buildBinary
nimscript.nim(273, 7)    exec
/Users/egonat/repos/codex-storage/nim-codex/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(273, 7) Error: unhandled exception: FAILED: nim c --out:build/codex -d:chronicles_runtime_filtering -d:chronicles_log_level=TRACE --verbosity:0 --hints:off -d:release ./codex.nim [OSError]
make: *** [all] Error 1
```

Bizarrely, it seems that this does compile on Windows and Linux.

**Comment by emizzle** [comment]
The [`err` example from above](https://github.com/codex-storage/nim-codex/blob/8aaff32b4669366ca468ef7eaf04e730412ab95d/codex/utils/poseidon2digest.nim#L68-L69) works on my machine running 1.6.20, but failed on CI running 1.6.21: https://github.com/codex-storage/nim-codex/actions/runs/11603964472/job/32311929139

**Comment by emizzle** [comment]
And here's an example that seemed to both compile on my machine (1.6.20) and in CI (1.6.21): 

https://github.com/codex-storage/nim-codex/pull/975/files#diff-1d1002c193df82f5e31f0bd8de08f3fc23075c9ec50e09bf9442ba839e37efd9R164-R166
